### ISSUE TITLE
duplicate instantiation of stockRuntimeClient

### ISSUE THREAD

**Issue by xxinran** [ease-lab/vhive#428]
The `stockRuntimeClient` is instantiated in NewFirecrackerService() function and is re-instantiated in `NewService()`. I wonder if it is a bug, or did I miss something.

Please see 
https://github.com/ease-lab/vhive/blob/main/cri/firecracker/service.go#L62 
https://github.com/ease-lab/vhive/blob/main/cri/service.go#L54

**Comment by xxinran** [comment]
Hi @nathanieltornow, thanks for your explanation. So the `fs.stockRuntimeClient` is specific for firecracker which is an attribute of FC service and it is listening on containerd.sock, while the `stockRuntimeClient` in cri.service is associated with `vhive-cri.sock`, please point it out if I misunderstood. 

Hi @ustiugov, thanks for the information, I am doing some benchmarking on serverless platform, and vhive gave me an opportunity to integrate firecracker with k8s.

**Comment by nathanieltornow** [comment]
Hi @xxinran 
No, both are communicating with the stock-containerd service. 
A quick explanation:
- the vHive-cri listens on `vhive-cri.sock` in order to serve all request from k8s.
- the vhive-cri simply forwards all those requests (except `CreateContainer` and `RemoveContainer`) to the stock containerd-cri, which listens on `/run/containerd/containerd.sock`. Those request are forwarded by using the stockRuntimeClient and stockImageClient.
- The requests `CreateContainer` and `RemoveContainer` are handled by the fcService (or gvisorService) which (in addition to forwarding the request to the stock containerd-cri via the "duplicated" stockRuntimeClient) are creating the microVMs (or sandboxes).

To conclude, we basically have two stockRuntimeClients: (1) one from the fcService (or gvisorService), (2) one from the generic cri.Service. Since both of those clients are just used to forward requests to the same service (the stock containerd-cri), we don't have an actual bug here. 
I think using just one client (shared by the fcService and the cri.Service) would have the same result.

**Comment by nathanieltornow** [comment]
I'll close this issue for now, we can reopen it if other questions or problems arise.
